demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  		@time = Time.now
  		
  end

  def goodbye
  		@files = Dir.glob('*')
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

<%= link_to('Hello', say_hello_path) %>
<%= 1+2 %>
<%= 'cow'+'boy' %>
<%= 1.hour.from_now.localtime %>

<ul>
	<% for file in @files %>
		<li><%= file %></li>
	<% end %>
</ul>

demo/app/views/say/hello.html.erb
<h1>Say#hello CHANGED</h1>
<p>Find me in app/views/say/hello.html.erb</p>
It is |<%= @time %>|<br/>

<a href="/say/goodbye">Exit</a>

<% puts "testme" %>
<%= 'adsad' %>

<% 99.downto(96) do |number| %>
  <%= number %> bottles of beer...
<% end %>